export const authErrors = [
  'INVALID_SESSION_INFORMATION',
  'NO_APP_KEY',
  'NO_SESSION',
  'INVALID_APP_KEY',
  'APP_KEY_CREATION_FAILED',
  'APP_CREATION_FAILED',
  'SUBSCRIPTION_EXPIRED',
  'INVALID_SUBSCRIPTION_TOKEN',
];

export const warningErrors = [
  'INVALID_INPUT_DATA',
  'UNEXPECTED_ERROR',
  'SERVICE_BUSY',
  'TIMEOUT_ERROR',
  'REQUEST_SIZE_EXCEEDS_LIMIT',
  'INVALID_CLIENT_REF',
  'TOO_MANY_REQUESTS',
  'WALLET_TRANSFER_ERROR',
  'TOO_MUCH_DATA',
  'ACCESS_DENIED',
];
